### ISSUE TITLE
Removing the line instead of changing to 0

### ISSUE THREAD

**Issue by kkmuffme** [tengattack/eslint-plugin-php-markup#1]
Hey,

would it be possible to remove things within <?php ... ?> completely instead of changing them to 0 if the the <?php is preceeded by whitespace or newline?

e.g.

```
function valueAddedToCart( final_result ) {
	<?php 
	if ( $someVar == $otherVar ) { ?>
		fbq( 'track', 'AddToCart', {
			'content_ids': '<?php echo $product_id; ?>',
		});
	<?php } ?>
}
```

here line 2 & 7 will throw errors in eslint (for many rules) bc the php-markup changes them to 0 like:

```
function valueAddedToCart( final_result ) {
	0
		fbq( 'track', 'AddToCart', {
			'content_ids': '0',
		});
	0
}
```

if instead it would only change things in <?php ... ?> to 0 that are NOT preceeded by whitespace/newline it would look like:

```
function valueAddedToCart( final_result ) {
		fbq( 'track', 'AddToCart', {
			'content_ids': '0',
		});
}
```

which then would give correct results

**Comment by tengattack** [comment]
Which version of `eslint` and `eslint-plugin-html` do you used?

**Comment by tengattack** [comment]
now https://github.com/tengattack/eslint-plugin-php-markup/commit/944053167491bcf1c0e285d98e99040633357f8d can do that through `settings`:

```js
{
  // ...
  "settings": {
    "php/markup-replacement": {"php": "", "=": "0"},
  },
  // ...
}
```
- `<?php ... ?>` would be replaced by `php`'s value
- `<?= ... ?>` would be replaced by `=`'s value

**Comment by tengattack** [comment]
Did you mean we should provide an option to remove the entire lines which contain php tag only?

It will remove the CRLF just after PHP tag by default, unless we set `keep-eol` to true in settings.

And your code will be (keep-eol):
```js
function valueAddedToCart( final_result ) {
	
		fbq( 'track', 'AddToCart', {
			'content_ids': '',
		});
	
}
```

I think it will show errors by rule `no-trailing-spaces`? So that we have to make an option remove entire empty line after remove the php tag. I will check it later and try to find a way to fix it.

**Comment by tengattack** [comment]
48ce52d9e76de06265df1b142f801b3d10700b1a may help you with settings `php/remove-empty-line` will remove empty line now.

**Comment by kkmuffme** [comment]
Problem is when using like this with the php "", and = "0" option, that we will get false positive errors.
e.g.
productListCheckout = <?php echo json_encode($product_detail); ?>;

will trigger:
Parsing error: Unexpected token ;

Thats why I suggested the solution with the newline+whitespace.
if <?php ...?> is preceeded by ^ (beginning of file) OR newline (\n or \r\n) + whitespace [\t ]{1,}
in regex: (^|\n|\r\n)[\t ]{1,}

=> then replace it with empty, else replace it with 0.

**Comment by tengattack** [comment]
I mean we can change the `<?php echo` to `<?=` which is enabled by default since [5.4](http://php.net/manual/en/migration54.new-features.php), so that you can change it to 0.

**Comment by tengattack** [comment]
@kkmuffme now v0.2.4 support it!

**Comment by kkmuffme** [comment]
Thanks a lot, I think I don't get which settings to use (or maybe there's a bug).

I updated to 0.2.4 first. Then I tried this:

```
        "php/markup-replacement": {"php": "0", "=": "0"},
        "php/keep-eol": true,
        "php/remove-whitespace": true,
        "php/remove-empty-line": true
```


```
<script>
function valueAddedToCart( final_result ) {
	<?php 
	if ( $someVar == $otherVar ) { ?>
		fbq( 'track', 'AddToCart', {
			'content_ids': '<?php echo $product_id; ?>',
		});
	<?php } ?>
}
</script>
```

will still result in this:

```
<script>
function valueAddedToCart( final_result ) {
	fbq( 'track', 'AddToCart', {
		'content_ids': '<?php echo $product_id; ?>'
	});
<?php } ?>
}
</script>
```

What would be the correct config for this to work?

**Comment by kkmuffme** [comment]
Perfect works now. Thanks a lot!
