### ISSUE TITLE
Not compatible with eslint 6.x

### ISSUE THREAD

**Issue by kkmuffme** [tengattack/eslint-plugin-php-markup#3]
It seems like the plugin is not compatible with eslint 6.x

Error: Failed to load plugin 'php-markup' declared in '--config': eslint-plugin-php-markup error: It seems that eslint is not loaded.

I had this same error with eslint-plugin-html, but they fixed the compatibility issue in v6.0.0 (if that is any help for you)

**Comment by tengattack** [comment]
Ok, I will take a look later

**Comment by kkmuffme** [comment]
@tengattack could you take a look at the issue this week? would be greatly appreciated as it's a great tool but can't be used right now :-(

**Comment by tengattack** [comment]
Sorry for the later, I have upgrade the plugin to `v6.0.0` which is compatible with eslint 6.x!

Could you have a try?

**Comment by kkmuffme** [comment]
Perfect works. Thanks a lot!
